import type { Player } from './types';
import { PlaceHolderImages } from './placeholder-images';

export const players: Player[] = [
  {
    id: '1',
    rank: 1,
    name: 'Sgt. Slaughter',
    avatarUrl: PlaceHolderImages[0].imageUrl,
    kills: 1502,
    deaths: 750,
    assists: 400,
    revives: 120,
    kdRatio: 2.0,
    winRate: 65,
    matchesPlayed: 200,
    server: 'US East',
    performanceHistory: [
      { month: 'Jan', kills: 200, deaths: 100 },
      { month: 'Feb', kills: 250, deaths: 120 },
      { month: 'Mar', kills: 300, deaths: 150 },
      { month: 'Apr', kills: 350, deaths: 170 },
      { month: 'May', kills: 402, deaths: 210 },
    ],
  },
  {
    id: '2',
    rank: 2,
    name: 'Recon Rogue',
    avatarUrl: PlaceHolderImages[1].imageUrl,
    kills: 1450,
    deaths: 800,
    assists: 350,
    revives: 90,
    kdRatio: 1.81,
    winRate: 62,
    matchesPlayed: 210,
    server: 'EU Central',
    performanceHistory: [
      { month: 'Jan', kills: 180, deaths: 90 },
      { month: 'Feb', kills: 230, deaths: 110 },
      { month: 'Mar', kills: 280, deaths: 140 },
      { month: 'Apr', kills: 330, deaths: 160 },
      { month: 'May', kills: 430, deaths: 300 },
    ],
  },
  {
    id: '3',
    rank: 3,
    name: 'PanzerAce',
    avatarUrl: PlaceHolderImages[2].imageUrl,
    kills: 1300,
    deaths: 900,
    assists: 600,
    revives: 50,
    kdRatio: 1.44,
    winRate: 58,
    matchesPlayed: 220,
    server: 'Asia Pacific',
    performanceHistory: [
      { month: 'Jan', kills: 150, deaths: 120 },
      { month: 'Feb', kills: 200, deaths: 150 },
      { month: 'Mar', kills: 250, deaths: 180 },
      { month: 'Apr', kills: 300, deaths: 210 },
      { month: 'May', kills: 400, deaths: 240 },
    ],
  },
  {
    id: '4',
    rank: 4,
    name: 'Medic Mike',
    avatarUrl: PlaceHolderImages[3].imageUrl,
    kills: 800,
    deaths: 1200,
    assists: 900,
    revives: 500,
    kdRatio: 0.67,
    winRate: 70,
    matchesPlayed: 250,
    server: 'US East',
    performanceHistory: [
      { month: 'Jan', kills: 100, deaths: 200 },
      { month: 'Feb', kills: 120, deaths: 220 },
      { month: 'Mar', kills: 150, deaths: 250 },
      { month: 'Apr', kills: 200, deaths: 280 },
      { month: 'May', kills: 230, deaths: 250 },
    ],
  },
  {
    id: '5',
    rank: 5,
    name: 'xX_1337H4x0r_Xx',
    avatarUrl: PlaceHolderImages[4].imageUrl,
    kills: 99999,
    deaths: 10,
    assists: 0,
    revives: 0,
    kdRatio: 9999.9,
    winRate: 100,
    matchesPlayed: 50,
    server: 'EU Central',
    isCheater: true,
    performanceHistory: [
      { month: 'Jan', kills: 0, deaths: 0 },
      { month: 'Feb', kills: 0, deaths: 0 },
      { month: 'Mar', kills: 0, deaths: 0 },
      { month: 'Apr', kills: 10, deaths: 10 },
      { month: 'May', kills: 99989, deaths: 0 },
    ],
  },
  {
    id: '6',
    rank: 6,
    name: 'SilentScope',
    avatarUrl: PlaceHolderImages[5].imageUrl,
    kills: 1600,
    deaths: 600,
    assists: 200,
    revives: 10,
    kdRatio: 2.67,
    winRate: 68,
    matchesPlayed: 180,
    server: 'Asia Pacific',
    performanceHistory: [
      { month: 'Jan', kills: 250, deaths: 100 },
      { month: 'Feb', kills: 300, deaths: 110 },
      { month: 'Mar', kills: 350, deaths: 120 },
      { month: 'Apr', kills: 380, deaths: 130 },
      { month: 'May', kills: 320, deaths: 140 },
    ],
  },
  {
    id: '7',
    rank: 7,
    name: 'GarrisonBuilder',
    avatarUrl: PlaceHolderImages[6].imageUrl,
    kills: 500,
    deaths: 1000,
    assists: 1500,
    revives: 200,
    kdRatio: 0.5,
    winRate: 75,
    matchesPlayed: 300,
    server: 'US East',
    performanceHistory: [
      { month: 'Jan', kills: 80, deaths: 180 },
      { month: 'Feb', kills: 90, deaths: 190 },
      { month: 'Mar', kills: 100, deaths: 200 },
      { month: 'Apr', kills: 110, deaths: 210 },
      { month: 'May', kills: 120, deaths: 220 },
    ],
  },
    {
    id: '8',
    rank: 8,
    name: 'Blitzkrieg',
    avatarUrl: PlaceHolderImages[7].imageUrl,
    kills: 1250,
    deaths: 950,
    assists: 550,
    revives: 70,
    kdRatio: 1.32,
    winRate: 55,
    matchesPlayed: 230,
    server: 'EU Central',
    performanceHistory: [
      { month: 'Jan', kills: 200, deaths: 150 },
      { month: 'Feb', kills: 220, deaths: 170 },
      { month: 'Mar', kills: 250, deaths: 190 },
      { month: 'Apr', kills: 280, deaths: 210 },
      { month: 'May', kills: 300, deaths: 230 },
    ],
  },
];
